apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-jupyter-liyi-ingress
  namespace: fsi-ray # 作用于 fsi-ray 命名空间
spec:
  podSelector: {} # 允许所有 Pod 接收来自 jupyter-liyi 的流量 (根据端口限制)
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: jupyterhub
          podSelector:
            matchLabels:
              app: jupyter-liyi
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 10001
  policyTypes:
    - Ingress
