apiVersion: v1
kind: Namespace
metadata:
  name: fsi-ray-cpu-data-scientist

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-shared-ray-cpu-data-scientist
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-fc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-002da5cf92091b392 # 替换为实际的 EFS 文件系统 ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-shared-ray-cpu-data-scientist
  namespace: fsi-ray-cpu-data-scientist
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-fc
  resources:
    requests:
      storage: 100Gi

---
apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: fsi-ray-cpu-data-scientist
  namespace: fsi-ray-cpu-data-scientist
spec:
  rayVersion: '2.35.0'
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      spec:
        volumes:
          - name: efs-shared-ray-cpu-data-scientist
            persistentVolumeClaim:
              claimName: efs-shared-ray-cpu-data-scientist
        nodeSelector:
          type: karpenter
          NodeGroupType: x86-cpu-karpenter
        containers:
          - name: ray-head
            image: rayproject/ray-ml:2.35.0.deprecated-py311-cpu
            resources:
              limits:
                cpu: 3
                memory: 14Gi
              requests:
                cpu: 2
                memory: 10Gi
            volumeMounts:
              - name: efs-shared-ray-cpu-data-scientist
                mountPath: /home/shared
                subPath: shared
              - name: efs-shared-ray-cpu-data-scientist
                mountPath: /home/datascientist
                subPath: home/datascientist
            ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
  workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 5
      rayStartParams: {}
      groupName: cpu-group
      template:
        spec:
          volumes:
            - name: efs-shared-ray-cpu-data-scientist
              persistentVolumeClaim:
                claimName: efs-shared-ray-cpu-data-scientist
          containers:
            - name: ray-worker
              image: rayproject/ray-ml:2.35.0.deprecated-py311-cpu
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh","-c","ray stop"]
              volumeMounts:
                - name: efs-shared-ray-cpu-data-scientist
                  mountPath: /home/shared
                  subPath: shared
                - name: efs-shared-ray-cpu-data-scientist
                  mountPath: /home/datascientist
                  subPath: home/datascientist
              resources:
                limits:
                  cpu: 3
                  memory: 14Gi
                requests:
                  cpu: 2
                  memory: 10Gi

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fsi-ray-cpu-data-scientist-dashboard
  namespace: fsi-ray-cpu-data-scientist
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /fsi-ray-cpu-data-scientist-dashboard/dashboard/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: fsi-ray-head-svc
              port:
                number: 8265