apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  name: fsi-ray-cpu
  namespace: fsi-ray-cpu
spec:
  rayVersion: '2.6.0'
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      spec:
        volumes:
          - name: efs-shared-ray
            persistentVolumeClaim:
              claimName: efs-shared-ray
        nodeSelector:
          type: karpenter
          NodeGroupType: x86-cpu-karpenter
        containers:
          - name: ray-head
            image: rayproject/ray-ml:2.6.0
            resources:
              limits:
                cpu: 3
                memory: 14Gi
              requests:
                cpu: 2
                memory: 10Gi
            volumeMounts:
              - name: efs-shared-ray
                mountPath: /mnt/efs-shared
            ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
  workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 5
      rayStartParams: {}
      groupName: cpu-group
      template:
        spec:
          containers:
            - name: ray-worker
              image: rayproject/ray-ml:2.6.0
              lifecycle:
                preStop:
                  exec:
                    command: ["/bin/sh","-c","ray stop"]
              resources:
                limits:
                  cpu: 3
                  memory: 14Gi
                requests:
                  cpu: 2
                  memory: 10Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fsi-ray-dashboard
  namespace: fsi-ray-cpu
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
        - path: /fsi-ray/dashboard/(.*)
          pathType: ImplementationSpecific
          backend:
            service:
              name: fsi-ray-head-svc
              port:
                number: 8265